*======================================================================
* make_data.do  --  ONE-TIME data construction (author-only)
*
* This script is NOT part of the reproducible pipeline in main.do. It
* documents how the two raw sources were built and is provided for
* transparency. Replicators do not need to run it -- in a real package
* the confidential source could not be regenerated by an outsider anyway.
*
* It writes the two raw sources the package treats as GIVEN inputs:
*   data/raw/firm_registry.dta             -- public characteristics
*   data/raw-confidential/firm_survey.dta  -- CONFIDENTIAL outcomes,
*        excluded from the redistributed output via .sivacorignore
*
* Run standalone from the package root:   do make_data.do
*======================================================================

clear all
set more off
version 14

* Paths (run from the package root, so cwd is the root)
global rootdir "`c(pwd)'"
global rawdata "$rootdir/data/raw"
global rawconf "$rootdir/data/raw-confidential"

cap mkdir "$rootdir/data"
cap mkdir "$rawdata"
cap mkdir "$rawconf"

* Fixed seed for reproducible construction
set seed 20260627

clear
set obs 500
gen long firm_id = _n

* ---- latent firm attributes (used to build both sources) -------------
gen byte   industry = 1 + int(runiform()*5)            // sector 1..5
gen byte   region   = 1 + int(runiform()*4)            // region 1..4
gen double lcapital = rnormal(10, 1)                   // log capital stock
gen double lemp     = 0.6*lcapital + rnormal(0, 0.5)   // log employment

* industry-specific productivity shifter
gen double ind_fe = 0
forvalues k = 1/5 {
    replace ind_fe = 0.10*`k' if industry == `k'
}

* outcome: log revenue (the relationship 03_analysis recovers)
gen double lrevenue = 2 + 0.5*lcapital + 0.4*lemp + ind_fe + rnormal(0, 0.4)

* ---- Source A: firm registry (PUBLIC characteristics) ---------------
preserve
    keep firm_id industry region lcapital
    rename lcapital log_capital
    label var firm_id     "Firm identifier"
    label var industry    "Industry sector (1-5)"
    label var region      "Region code (1-4)"
    label var log_capital "Log of capital stock"
    label data "Source A: firm registry (simulated, public)"
    save "$rawdata/firm_registry.dta", replace
restore

* ---- Source B: firm survey (CONFIDENTIAL outcomes) ------------------
preserve
    keep firm_id lemp lrevenue
    rename lemp     log_employment
    rename lrevenue log_revenue
    * simulate ~5% survey non-response -> these firms are missing in B
    drop if runiform() < 0.05
    label var firm_id        "Firm identifier"
    label var log_employment "Log of employment"
    label var log_revenue    "Log of revenue"
    label data "Source B: firm survey (simulated, confidential)"
    save "$rawconf/firm_survey.dta", replace
restore

display as result "make_data.do: wrote firm_registry.dta (public) and " ///
    "firm_survey.dta (confidential)"
